// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrduU8c1r8Qazxvco4T6-SjMcbFz3eKvw',
    appId: '1:586675089673:web:fbbfa01bbaf8887a3d23d8',
    messagingSenderId: '586675089673',
    projectId: 'flash-chat-a1d68',
    authDomain: 'flash-chat-a1d68.firebaseapp.com',
    storageBucket: 'flash-chat-a1d68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoO4ZYRdoixCMwVAYuMFRemzdr3F5CV7o',
    appId: '1:586675089673:android:6768ffdadefe48953d23d8',
    messagingSenderId: '586675089673',
    projectId: 'flash-chat-a1d68',
    storageBucket: 'flash-chat-a1d68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0vbleEiMYSmd3cD8Ff7_AEBFZwjZBXms',
    appId: '1:586675089673:ios:f934d9a81da1b2b63d23d8',
    messagingSenderId: '586675089673',
    projectId: 'flash-chat-a1d68',
    storageBucket: 'flash-chat-a1d68.appspot.com',
    iosClientId: '586675089673-dl6i1fi7cavu07f92pco6j8rl17pua5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0vbleEiMYSmd3cD8Ff7_AEBFZwjZBXms',
    appId: '1:586675089673:ios:f934d9a81da1b2b63d23d8',
    messagingSenderId: '586675089673',
    projectId: 'flash-chat-a1d68',
    storageBucket: 'flash-chat-a1d68.appspot.com',
    iosClientId: '586675089673-dl6i1fi7cavu07f92pco6j8rl17pua5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
